-- Seed existing blog posts into Supabase blog_posts table
-- Run this AFTER creating the table with blog_posts_schema.sql

INSERT INTO public.blog_posts (slug, title, description, date, tag, tag_bg, content, faq, is_published) VALUES

('how-to-score-seven-point-five-in-ielts',
 'How to Score 7.5+ in IELTS on Your First Attempt',
 'A comprehensive guide on listening, speaking, reading, and writing patterns with mock test preparation guidelines.',
 'Jun 28, 2026',
 'STUDY PREP',
 'bg-blue-50 border-blue-100 text-blue-700',
 '<h2>Cracking the IELTS Exam</h2><p>Scoring a 7.5+ band on your first attempt in IELTS requires structured practice, familiarity with the format, and specific test-taking strategies. The IELTS exam tests four core modules: Listening, Reading, Writing, and Speaking.</p><h3>1. Listening: Train Your Ear</h3><p>Listening is the easiest module to score 8.0+ if you practice active listening. Pay attention to plurals, numbers, spelling, and synonyms. Watch British and Australian media to get familiar with different accents.</p><h3>2. Reading: Skimming &amp; Scanning</h3><p>Do not read every word of the passages. Practice skimming (reading quickly for the general idea) and scanning (searching for specific keywords and figures). Remember, answers follow the order of the text in most question types.</p><h3>3. Writing: Structure and Vocabulary</h3><p>Writing consists of two tasks. For Task 1 (graphs/charts), focus on summarizing trends. For Task 2 (essays), structure your response clearly: Introduction, 2 Body Paragraphs with examples, and a Conclusion. Use formal vocabulary and varied sentence structures.</p><h3>4. Speaking: Fluency Over Perfect Accents</h3><p>Speak naturally, expand on your answers, and use connectors. The examiner is checking your grammatical range, fluency, and pronunciation, not your accent. Practice with daily mock speaking sessions.</p>',
 '[{"q":"Is IELTS mandatory for study abroad?","a":"Yes, for most English-speaking countries, but waiver options (like MOI) exist under specific university rules."},{"q":"How long is my IELTS score valid?","a":"IELTS scores are valid for 2 years from the date of the test."}]'::jsonb,
 true),

('writing-a-winning-sop-for-canadian-dlis',
 'Writing a Winning SOP for Top Canadian DLIs',
 'How to structure your Statement of Purpose (SOP) to explain study intentions and home ties clearly to visa officers.',
 'Jun 24, 2026',
 'SOP GUIDE',
 'bg-purple-50 border-purple-100 text-purple-700',
 '<h2>The Anatomy of a High-Conversion SOP</h2><p>A Statement of Purpose (SOP) is a personal essay that details your academic background, career goals, and reasons for choosing a specific program in Canada. It is the single most important document scrutinized by Canadian immigration officers.</p><h3>Key Sections of a Strong Canadian SOP:</h3><ul><li><strong>Academic History &amp; Achievements:</strong> Discuss your relevant academic milestones and how they connect to your chosen course.</li><li><strong>Reason for Choosing Canada:</strong> Explain why Canada is your target study destination over India or other countries.</li><li><strong>Institution Selection:</strong> Detail why you selected that specific Designated Learning Institution (DLI) and the course modules that interest you.</li><li><strong>Future Career Plans:</strong> Mention specific roles, sectors, and employers in India that you plan to join after graduation.</li><li><strong>Proof of Home Ties:</strong> Crucially establish family assets, relationships, and socio-economic reasons to return to India upon completion.</li></ul><h3>Common SOP Mistakes to Avoid:</h3><p>Avoid copying templates from the internet. Plagiarism is an automatic refusal flag. Ensure your financial capabilities match the tuition and GIC receipts attached to your file.</p>',
 '[{"q":"How long should a Canada SOP be?","a":"Ideally, it should be between 800 to 1,200 words, structured across 1 to 2 pages."},{"q":"Do I need to sign my SOP?","a":"Yes, a signed and dated SOP adds professional credibility to your visa file."}]'::jsonb,
 true),

('understanding-public-university-free-tuition-germany',
 'Understanding Public University Free Tuition in Germany',
 'A detailed breakdown of Semesterbeitrag fees, Uni-Assist application routes, and blocked account limits.',
 'Jun 20, 2026',
 'GERMANY GUIDE',
 'bg-emerald-50 border-emerald-100 text-emerald-700',
 '<h2>Free Education in Germany</h2><p>German public universities have offered tuition-free education to both domestic and international students since 2014. Here is how you can leverage this system to earn a world-class degree on a minimal budget.</p><h3>1. The Zero-Tuition Concept</h3><p>Instead of tuition, students only pay a nominal semester fee (Semesterbeitrag) ranging from €150 to €350. This fee covers student union services, university administration, and a regional transit pass (Semesterticket) allowing free public transport.</p><h3>2. The Blocked Account Requirement</h3><p>To secure a German student visa, you must prove you can support yourself financially. You do this by opening a Blocked Account (Sperrkonto) and depositing €11,208. The bank releases €934 per month for your living expenses during your first year.</p><h3>3. The Uni-Assist Portal</h3><p>Many German universities process international student files via the centralized Uni-Assist portal. Uni-Assist evaluates your transcripts, converts your grades to the German GPA scale, and forwards your application to the university.</p>',
 '[{"q":"Are English-taught courses free in Germany?","a":"Yes, public university courses taught in English are tuition-free, though admission is highly competitive."},{"q":"Can I work part-time in Germany?","a":"Yes, international students can work 120 full days or 240 half days per year."}]'::jsonb,
 true),

('documents-required-for-canada-student-visa-from-india',
 'Documents Required for Canada Student Visa from India',
 'A complete checklists guide outlining all mandatory SDS and Non-SDS documents required for a Canadian study permit.',
 'Jul 01, 2026',
 'STUDY VISA',
 'bg-red-50 border-red-100 text-red-700',
 '<h2>Documents Required for Canada Student Visa from India 2026</h2><p>Filing a Canadian study permit requires strict adherence to the document list. Even a single missing paper can result in visa processing delays or immediate refusal. Below is the complete checklist for Indian applicants under the standard SDS and Non-SDS routes.</p><h3>Mandatory Documents Checklist:</h3><ol><li><strong>Letter of Acceptance (LOA):</strong> Official acceptance letter issued by a Designated Learning Institution (DLI) in Canada.</li><li><strong>Provincial Attestation Letter (PAL):</strong> Mandatory attestation letter issued by the province where your university is located.</li><li><strong>Proof of Identity:</strong> A valid passport with at least 6 months validity.</li><li><strong>Guaranteed Investment Certificate (GIC):</strong> GIC receipt showing payment of CAD 20,635 as proof of living funds.</li><li><strong>Tuition Fee Receipt:</strong> Receipt proving payment of the first-year tuition fee.</li><li><strong>Language Proficiency Scores:</strong> Academic IELTS (minimum 6.0 in each band) or PTE equivalent.</li><li><strong>Upfront Medical Exam:</strong> Receipt or certificate of medical check-up at an empanelled physician.</li><li><strong>SOP &amp; Academic Transcripts:</strong> Statement of Purpose detailing study intent, along with graduation and school marksheets.</li></ol><h3>SDS vs Non-SDS Processing:</h3><p>The Student Direct Stream (SDS) offers faster processing times (often under 20 days) for applicants meeting the GIC and language requirements. Non-SDS applies if you are submitting alternative financial support (like liquid assets, income taxes, or sponsor proofs) instead of a GIC.</p>',
 '[{"q":"Is a GIC mandatory for a Canadian student visa?","a":"Yes, it is practically mandatory for SDS. For Non-SDS, you must show equivalent liquid funds in Indian bank accounts."},{"q":"What is a PAL?","a":"A Provincial Attestation Letter is a document issued by the local Canadian province validating your study permit quota."}]'::jsonb,
 true),

('ielts-score-required-for-australia-pr-2026',
 'IELTS Score Required for Australia PR 2026',
 'Calculate your skilled migration points. A detailed breakdown of IELTS band requirements for subclass 189/190 Australia PR.',
 'Jul 01, 2026',
 'AUSTRALIA PR',
 'bg-blue-50 border-blue-100 text-blue-700',
 '<h2>IELTS Requirements for Australia PR in 2026</h2><p>Australia''s General Skilled Migration (GSM) points system rewards high English proficiency. Scoring well in IELTS or PTE is the fastest way to boost your points score and secure an Invitation to Apply (ITA).</p><h3>GSM Points Awarded by English Score:</h3><ul><li><strong>Superior English (IELTS 8.0 in all 4 bands / PTE 79+):</strong> Awards <strong>20 points</strong> toward your PR application.</li><li><strong>Proficient English (IELTS 7.0 in all 4 bands / PTE 65+):</strong> Awards <strong>10 points</strong>.</li><li><strong>Competent English (IELTS 6.0 in all 4 bands / PTE 50+):</strong> Required to meet minimum eligibility, but awards <strong>0 points</strong>.</li></ul><h3>Minimum Point Thresholds:</h3><p>While the nominal minimum score to submit an Expression of Interest (EOI) is 65 points, high-demand sectors like IT and Engineering require a score of 85+ to receive state nominations. Securing the 20 points from Superior English is often the decisive factor.</p>',
 '[{"q":"Does PTE Academic count for Australia PR?","a":"Yes, Australia accepts both IELTS General/Academic and PTE Academic for points calculation."},{"q":"Can I combine multiple IELTS tests to claim points?","a":"No, you must achieve the target score in a single sitting."}]'::jsonb,
 true),

('how-much-bank-balance-for-usa-visitor-visa',
 'How Much Bank Balance for USA Visitor Visa',
 'Understand financial proofs for US B1/B2 tourist visa. Learn how much money to show to avoid ties rejections.',
 'Jul 02, 2026',
 'USA VISITOR',
 'bg-indigo-50 border-indigo-100 text-indigo-700',
 '<h2>Financial Sufficiency for USA B1/B2 Visas</h2><p>One of the most common reasons for a US visitor visa rejection under Section 214(b) is the inability to prove sufficient funds. Many applicants ask: ''How much money must be in my bank account?'' Here is the practical guide to US tourist visa funding.</p><h3>1. The Reality of the ''Minimum Balance''</h3><p>The US Department of State does not specify any official minimum bank balance. The visa officer evaluates your financial profiling to determine if you can easily cover a trip costing roughly $3,000 to $5,000 without seeking illegal work in the US.</p><h3>2. Recommended Savings Profile</h3><p>For a standard 2-week tourist trip, we recommend showing a stable bank balance of <strong>₹3 Lakhs to ₹5 Lakhs per applicant</strong>. This should not be a sudden deposit; officers look for seasoned, gradual savings over a period of 6 months.</p><h3>3. Supporting Income Documents</h3><p>Liquid balance is only part of the story. You must attach stable income proofs to establish ties to India:<ul><li>Salaried: 3 years of Income Tax Returns (ITR), Form 16, and salary slips.</li><li>Business Owners: Company registration, GST certificates, and corporate bank statements.</li></ul></p>',
 '[{"q":"Can a sponsor in the USA cover my expenses?","a":"Yes, an American sponsor can submit Form I-134 (Affidavit of Support) along with tax records, though you must still prove ties to India."},{"q":"Will a low bank balance cause visa rejection?","a":"Yes, if the officer believes you cannot support yourself or your itinerary is disproportionate to your earnings."}]'::jsonb,
 true),

('germany-opportunity-card-eligibility-points-calculator',
 'Germany Opportunity Card Eligibility Points Calculator',
 'Calculate your Chancenkarte points. Learn the exact requirements for age, education, and language skills.',
 'Jul 03, 2026',
 'GERMANY CARD',
 'bg-emerald-50 border-emerald-100 text-emerald-700',
 '<h2>Germany Opportunity Card (Chancenkarte) Points Breakdown</h2><p>Germany''s Opportunity Card allows skilled professionals from non-EU nations to travel to Germany and seek employment. The qualification process uses a point system. You must score at least <strong>6 points</strong> out of 14 to qualify. Here is the points breakdown.</p><h3>Points Categories Explained:</h3><ul><li><strong>Foreign Degree Recognition (4 Points):</strong> Having a degree that is fully recognized in Germany (verified on the ANABIN database).</li><li><strong>Professional Experience (2 to 3 Points):</strong> 2 points for 2 years of work experience; 3 points for 5 years of experience in the last 7 years.</li><li><strong>Language Capabilities (1 to 3 Points):</strong> 1 point for basic German (A1) or English (B2); 2 points for German A2; 3 points for German B1.</li><li><strong>Age Group (1 to 2 Points):</strong> 2 points for applicants up to 35 years old; 1 point for age 35 to 40.</li><li><strong>Previous German Stay (1 Point):</strong> Lived in Germany for at least 6 months in the last 5 years.</li></ul><h3>Other Requirements:</h3><p>You must hold a recognized university degree or completed vocational training. Additionally, you must show proof of €12,324 (roughly €1,027/month) in a blocked account or an official guarantee letter from a sponsor in Germany.</p>',
 '[{"q":"Can I work on the Opportunity Card?","a":"Yes, you can work up to 20 hours per week in part-time/trial jobs while seeking full-time roles."},{"q":"What is the validity of the Chancenkarte?","a":"It is issued for up to 1 year and cannot be extended unless you find a qualifying job."}]'::jsonb,
 true),

('moi-accepted-universities-uk-for-indian-students',
 'MOI Accepted Universities UK for Indian Students',
 'Admission guide for UK. Read the list of British universities accepting Medium of Instruction certificates instead of IELTS.',
 'Jul 03, 2026',
 'UK STUDY',
 'bg-purple-50 border-purple-100 text-purple-700',
 '<h2>Study in UK Without IELTS: MOI Guide</h2><p>If you want to study in the United Kingdom but have not taken the IELTS exam, you may still qualify. Many top UK universities accept a Medium of Instruction (MOI) certificate. An MOI is an official document from your Indian school or college stating that your entire education was taught in English.</p><h3>Key UK Universities Accepting MOI:</h3><ul><li>University of Portsmouth</li><li>Sheffield Hallam University</li><li>University of Greenwich</li><li>Northumbria University</li><li>University of Central Lancashire (UCLan)</li><li>Bangor University</li></ul><h3>Standard Eligibility Criteria for MOI Waiver:</h3><p>To secure a waiver, you must have scored at least <strong>70% to 75% in English in your 10th and 12th grade board exams</strong> (CBSE, ICSE, or state boards like Gujarat Board). Your MOI certificate must be printed on official institutional letterhead with stamps and signatures.</p>',
 '[{"q":"Does UKVI accept MOI for student visas?","a":"Yes, the UK Home Office accepts university-sponsored CAS certificates that confirm the university has assessed your language skills via MOI."},{"q":"Can all Indian state boards get the waiver?","a":"Some universities restrict waivers to CBSE/ICSE boards, while others accept state boards if scores are above 75%."}]'::jsonb,
 true),

('january-2026-intake-universities-canada-uk-australia',
 'January 2026 Intake Universities Canada/UK/Australia',
 'Plan your applications. Check application deadlines, course availability, and list of universities for the winter intake.',
 'Jul 04, 2026',
 'INTAKE ALERTS',
 'bg-amber-50 border-amber-100 text-amber-700',
 '<h2>January 2026 Intake Deadlines &amp; Universities</h2><p>Missed the September intake? The January 2026 intake (also known as the Winter intake) is the perfect second chance. Applying for the winter cycle offers lower student competition and faster visa processing times. Here is the intake status across Canada, UK, and Australia.</p><h3>1. Canada Winter 2026</h3><p>Many colleges and Designated Learning Institutions (DLIs) accept applications for Business, IT, and Engineering diplomas. Major DLIs open: Conestoga College, Seneca College, and University of Windsor. <strong>Apply by August 2025.</strong></p><h3>2. United Kingdom January 2026</h3><p>UK universities offer a massive selection of 1-year postgraduate degrees during the January cycle. Target universities: Coventry University, University of Hertfordshire, and BPP University. <strong>Apply by September 2025.</strong></p><h3>3. Australia Semester 1 (February 2026)</h3><p>Australia''s primary academic cycle starts in February. All major Group of Eight and public universities are open for undergraduate and master''s degrees. <strong>Apply by October 2025.</strong></p>',
 '[{"q":"Are scholarships available in the January intake?","a":"Yes, universities offer equivalent bursaries, though the total quota might be slightly smaller than the fall cycle."},{"q":"When should I start my visa process for January?","a":"You should ideally secure your offer letter by September and file your visa by October."}]'::jsonb,
 true),

('study-abroad-without-ielts-for-indian-students',
 'Study Abroad Without IELTS for Indian Students',
 'A complete global guide detailing universities and countries that allow admissions based on school English grades or MOI.',
 'Jul 05, 2026',
 'STUDY ABROAD',
 'bg-emerald-50 border-emerald-100 text-emerald-700',
 '<h2>Global Study Guide: No IELTS Required</h2><p>Fearing the IELTS exam? Thousands of Indian students study abroad every year without taking the IELTS or PTE exams. Various countries offer alternative pathways to assess your English language proficiency.</p><h3>Country-Wise Waiver Opportunities:</h3><ul><li><strong>United Kingdom:</strong> Most widely accepted route. If you scored 70%+ in CBSE/ICSE 12th English, most universities will waive language tests.</li><li><strong>Germany:</strong> Private universities and selected English-taught public programs accept an Medium of Instruction (MOI) letter if your Bachelor''s degree was taught in English.</li><li><strong>Canada:</strong> Requires Non-SDS filing. Selected universities accept college diplomas, though visa approval odds are generally higher with a standard IELTS/PTE score.</li><li><strong>USA:</strong> Selected universities waive IELTS if you take internal university language tests or Duolingo English Test (DET) which is online and easier.</li></ul><h3>The Importance of MOI Certificates:</h3><p>An MOI (Medium of Instruction) certificate is the key document. It must explicitly state that your language of study and examination was English during your high school or college years.</p>',
 '[{"q":"Is Duolingo accepted instead of IELTS?","a":"Yes, over 4,000 institutions in the USA, Canada, and UK accept Duolingo online tests."},{"q":"Does studying without IELTS affect my visa success?","a":"It can increase scrutiny. Providing a strong Statement of Purpose (SOP) is critical to prove your fluency."}]'::jsonb,
 true)

ON CONFLICT (slug) DO NOTHING;
